---
title: "Untitled"
author: "Yibin Feng"
date: '2022-06-15'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}

# Split and scale data WITH SCALING
tmp.scaled <- Get_train_test_data(
  data.surv = data.surv, # Full surv data 
  data.long = data.long, # Full long data
  ids.test = ids.test.problematic, # Subject ids for test set
  is_scaled = "scaled", # Set to "scaled" to scale numeric covariates
  scaling_table = scaling_table
)
  
training.surv.scaled <- tmp.scaled$training.surv
training.long.scaled <- tmp.scaled$training.long

testing.surv.scaled <- tmp.notscaled$testing.surv
testing.long.scaled <- tmp.notscaled$testing.long


# Split and scale data NO SCALING
tmp.notscaled <- Get_train_test_data(
  data.surv = data.surv, # Full surv data 
  data.long = data.long, # Full long data
  ids.test = ids.test.problematic, # Subject ids for test set
  is_scaled = "notscaled", # Set to "scaled" to scale numeric covariates
  scaling_table = scaling_table
)
  
training.surv.notscaled <- tmp.notscaled$training.surv
training.long.notscaled <- tmp.notscaled$training.long

testing.surv.notscaled <- tmp.notscaled$testing.surv
testing.long.notscaled <- tmp.notscaled$testing.long
```


```{r}
for (x in vars_to_scale) {
  mu.notscaled <- mean(training.long.notscaled[, x], na.rm = TRUE) %>% round(3)
  sd.notscaled <- sd(training.long.notscaled[, x], na.rm = TRUE) %>% round(3)
  mu.scaled <- mean(training.long.scaled[, x], na.rm = TRUE) %>% round(3) 
  sd.scaled <- sd(training.long.scaled[, x], na.rm = TRUE) %>% round(3) 
  plot(training.long.scaled[, x], training.long.notscaled[, x])
  title(paste(x, 
              "\nmean", mu.notscaled,"sd", sd.notscaled,
              "mean", mu.scaled, "sd", sd.scaled))
}


```

```{r, fig.width=12}
training.long.scaled %>% 
  filter(id < 100) %>%
  ggplot(aes(x = age.fup, y = Entorhinal, color = factor(id))) +
    geom_line() + 
    geom_point()
```

```{r, fig.width=12}
training.long.notscaled %>% 
  filter(id < 100) %>%
  ggplot(aes(x = age.fup, y = Entorhinal, color = factor(id))) +
    geom_line() + 
    geom_point()
```

# [RESOLVED] Dive into survpred_prclmm

```{r, eval=FALSE}
library(nlme)
library(foreach)

times = deltaT # Prediction window(s) for surv prob prediction
new.longdata = testing.long # Long data in test set
new.basecovs = testing.surv

ranef.orig = step2$ranef.orig # 1453   41

baseline.covs = step3$call$baseline.covs
pcox.orig = step3$pcox.orig
surv.data = step3$surv.data
n = length(unique(surv.data$id))


#if (!is.null(new.longdata)) { 
  requireNamespace("nlme")

  lmms = step1$lmm.fits.orig
  y.names = step1$call.info$y.names # long vars
  fixefs = step1$call.info$fixefs
  
  p = length(y.names)
  ids = unique(new.longdata$id)
  n = length(ids)
  
  ranef.new = foreach(j = 1:p, .combine = "cbind") %do% 
    {
      new.df = new.longdata
      y = new.df[, y.names[j]]
      nas = which(is.na(y))
      if (length(nas) > 0) {
        new.df = new.df[-nas, ]
        y = new.df[, y.names[j]]
      }
      check = (length(unique(new.df$id)) == n)
      if (!check) {
        lost_ids = setdiff(new.longdata$id, new.df$id)
        mess = paste("Variable ", y.names[j], ": all values are NA for at least 1 subject.", 
          "Predictions obtained by setting predicted random effects for such subjects = 0 (population average)", 
          sep = "")
        warning(mess)
      }
      D.hat = getVarCov(lmms[[j]], type = "random.effects")
      beta.hat = fixef(lmms[[j]])
      sigma2.hat = summary(lmms[[j]])$sigma^2
      X = model.matrix(as.formula(fixefs), data = new.df)
      formYz = formula(lmms[[j]]$modelStruct$reStruct[[1]])
      mfZ = model.frame(terms(formYz), data = new.df)
      Z = model.matrix(formYz, mfZ)
      current = foreach(i = 1:n, .combine = "rbind") %do% 
        {
          rows = which(new.df$id == ids[i])
          if (length(rows) > 0) {
            Xi = X[rows, , drop = FALSE]
            yi = y[rows]
            Zi = Z[rows, , drop = FALSE]
            I.matr = diag(1, length(rows), length(rows))
            Vi = Zi %*% D.hat %*% t(Zi) + sigma2.hat * 
              I.matr
            temp = yi - Xi %*% beta.hat
            t(D.hat %*% t(Zi) %*% solve(Vi) %*% temp)
          }
          else {
            matrix(0, 1, length(beta.hat))
          }
        }
      current
    }
  
  rownames(ranef.new) = ids
#}



if (is.null(baseline.covs)) {
  X.orig = as.matrix(ranef.orig)
  rownames(X.orig) = rownames(ranef.orig)
  if (!is.null(new.longdata)) {
    X.new = as.matrix(ranef.new)
    rownames(X.new) = ids
  }
}
if (!is.null(baseline.covs)) {
  X0 = model.matrix(as.formula(baseline.covs), data = surv.data)
  X.orig = as.matrix(cbind(X0, ranef.orig))
  rownames(X.orig) = rownames(ranef.orig)
  contains.int = "(Intercept)" %in% colnames(X.orig)
  if (contains.int) {
    X.orig = X.orig[, -1, drop = FALSE]
  }
  if (!is.null(new.longdata)) {
    if (is.null(new.basecovs)) {
      stop("new.basecovs was not supplied")
    }
    X0 = model.matrix(as.formula(baseline.covs), data = new.basecovs)
    X.new = as.matrix(cbind(X0, ranef.new))
    rownames(X.new) = ids
    contains.int = "(Intercept)" %in% colnames(X.new)
    if (contains.int) {
      X.new = X.new[, -1, drop = FALSE]
    }
  }
}
```

```{r, eval=FALSE}
j = 5

new.df = new.longdata
y = new.df[, y.names[j]]
nas = which(is.na(y))
if (length(nas) > 0) {
  new.df = new.df[-nas, ]
  y = new.df[, y.names[j]]
}

check = (length(unique(new.df$id)) == n)
if (!check) {
  lost_ids = setdiff(new.longdata$id, new.df$id)
  mess = paste("Variable ", y.names[j], ": all values are NA for at least 1 subject.", 
    "Predictions obtained by setting predicted random effects for such subjects = 0 (population average)", 
    sep = "")
  warning(mess)
}
D.hat = getVarCov(lmms[[j]], type = "random.effects")
beta.hat = fixef(lmms[[j]])
sigma2.hat = summary(lmms[[j]])$sigma^2

X = model.matrix(as.formula(fixefs), data = new.df)
formYz = formula(lmms[[j]]$modelStruct$reStruct[[1]])
mfZ = model.frame(terms(formYz), data = new.df)
Z = model.matrix(formYz, mfZ)

# issues here
current = foreach(i = 1:n, .combine = "rbind") %do% 
  {
    rows = which(new.df$id == ids[i])
    
    if (length(rows) > 0) {
      Xi = X[rows, , drop = FALSE]
      yi = y[rows]
      Zi = Z[rows, , drop = FALSE]
      I.matr = diag(1, length(rows), length(rows))
      Vi = Zi %*% D.hat %*% t(Zi) + sigma2.hat * 
        I.matr
      temp = yi - Xi %*% beta.hat
      t(D.hat %*% t(Zi) %*% solve(Vi) %*% temp)
      #out = t(D.hat %*% t(Zi) %*% solve(Vi) %*% temp)
      #length(out)
    }
    else {
      matrix(0, 1, length(beta.hat))
      #matrix(0, 1, length(beta.hat)) %>% length()
    }
  }

which(current == 2)


```

