---
title: "Untitled"
author: "Yibin Feng"
date: '2022-05-26'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Dependencies

```{r}
library(tidyverse)

library(survival)
library(survminer)
```

# Import data

```{r}
load("adni_cleaned_prc.RData")
```


# Try Cox-base

```{r}

cox <- coxph(Surv(time, status=="dementia") ~ PTGENDER + AGE + PTEDUCAT, data = df.surv_preds)

summary(cox)

cox_fit <- survfit(cox)
autoplot(cox_fit)

# Do I need to factor categorical variables?
```



```{r}


cox <- coxph(Surv(time, status=="dementia") ~ PTGENDER + AGE + PTEDUCAT + APOE4, data = df.surv_preds)

summary(cox)

nd <- df.surv_preds[1:3,]
nd$APOE4 <- c(0, 1, 2)

cox_fit <- survfit(cox, newdata = nd)

plot(cox_fit, col = 2:4)
legend("topright", legend = 0:2, lty = 1, col = 2:4)

# autoplot(cox_fit) # Does not work?
```



```{r, eval=FALSE}
# Not ready

# try to factorize covariates
temp <- df.surv_preds
temp$PTGENDER <- temp$PTGENDER %>% factor()
temp$PTEDUCAT <- temp$PTEDUCAT %>% factor()
temp$APOE4 <- temp$APOE4 %>% factor()

cox <- coxph(Surv(time, status=="dementia") ~ PTGENDER + AGE + PTEDUCAT + APOE4, data = df.surv_preds)

summary(cox)
cox_fit <- survfit(cox)
autoplot(cox_fit)

# prepare new df
nd <- temp[1:3,]
nd$APOE4 <- 0:2
nd$APOE4 <- factor(nd$APOE4, levels = 0:2, labels = levels(temp$APOE4))

cox_fit <- survfit(cox, newdata = nd)

plot(cox_fit, col = 2:4)
legend("topright", legend = 0:2, lty = 1, col = 2:4)

# autoplot(cox_fit) # Does not work?
```