---
title: "run_funest"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, eval=FALSE}
install.packages("MFPCA")
install.packages("ranger")
install.packages("pec")
install.packages("tdROC")
install.packages("Rdpack")

install.packages("./package/funest_0.0.1.3.tar.gz", repos = NULL, type = "source")
```



```{r}
library(tidyverse)

library(funest)
```


# Example data

```{r}
data(long_test)
data(long_train)

data(surv_test)
data(surv_train)
```


```{r}
# Data format
surv_train %>% head()
```

```{r, eval=FALSE}
View(long_train)
```



```{r}
long_train %>% 
  pivot_longer(cols = c("Y1", "Y2", "Y3"), names_to = "time_var") %>%
  ggplot() + 
    geom_point(aes(obstime, value, group = id), alpha = 0.2) + 
    geom_line(aes(obstime, value, group = id), alpha = 0.2) + 
    facet_wrap(facets = "time_var")
```

```{r}
long_train %>% 
  group_by(id) %>%
  is.na() %>%
  sum()

# There is no NA values in the longitudinal covariates
```

# Example model

```{r}
help(package = "funest")
```

```{r}
# Example

w <- funest_fit(long_train %>% select(id, Y1, Y2, Y3, obstime), 
                surv_train, 
                tv_names = list("Y1", "Y2", "Y3"), 
                fv_names = list("W"), 
                noftree = 10, 
                t_star = 5.5, t_pred = 11)

# t_star: time for the last observed biomarker measurement
# t_pred: time at prediction

predictSurvProb.ranger <- predictor_loader() # must run the following code before calling funest_pred()

pred <- funest_pred(w, 
                    long_test %>% select(id, Y1, Y2, Y3, obstime), 
                    surv_test, 
                    tv_names = list("Y1", "Y2", "Y3"),
                    fv_names = list("W"), 
                    t_star = 5.5, t_pred = 11)
```

```{r}
# model output
w
```


```{r}
pred$bs
pred$AUC
pred$pred_pb
```

# Simulation - add NA values in longitudinal covariates

case 1 - it works
```{r}
# case 1 - all NA in one row

# Copy original simulated data
long_train_NA <- long_train

long_train_NA[1, "Y1"] <- NA
long_train_NA[1, "Y2"] <- NA
long_train_NA[1, "Y3"] <- NA

View(long_train_NA)
```

case 2 - 

```{r}
# case 2 - id=1 only has one obs row, other two obs are NAs

# Copy original simulated data
long_train_NA <- long_train

long_train_NA[2, "Y1"] <- NA
long_train_NA[2, "Y2"] <- NA
long_train_NA[2, "Y3"] <- NA

long_train_NA[3, "Y1"] <- NA
long_train_NA[3, "Y2"] <- NA
long_train_NA[3, "Y3"] <- NA

View(long_train_NA)
```

case 3 - it works
```{r}
# random NA, 25%

# Copy original simulated data
long_train_NA <- long_train

set.seed(721)

for (x in c("Y1", "Y2", "Y3")){
  long_train_NA[sample(1:nrow(long_train_NA), round(nrow(long_train_NA)*0.5)), x] <- NA # 25% obs randomly set to NA
}

View(long_train_NA)
```

```{r}
# Fit model
w <- funest_fit(long_train_NA %>% select(id, Y1, Y2, Y3, obstime), 
                surv_train, 
                tv_names = list("Y1", "Y2", "Y3"), 
                fv_names = list("W"), 
                noftree = 10, 
                t_star = 5.5, t_pred = 11)
```

```{r}
w
```

```{r}
predictSurvProb.ranger <- predictor_loader() # must run the following code before calling funest_pred()

pred <- funest_pred(w, 
                    long_test %>% select(id, Y1, Y2, Y3, obstime), 
                    surv_test, 
                    tv_names = list("Y1", "Y2", "Y3"),
                    fv_names = list("W"), 
                    t_star = 5.5, t_pred = 11)
```

```{r}
pred$bs
pred$AUC
pred$pred_pb
```


# ADNI

```{r}
load("adni_cleaned_prc.RData")
```

# ADNI

```{r}
# Prepare surv table
df.surv_preds_funest <- df.surv_preds_prc %>% 
  select(id, time, event, AGE, PTGENDER, PTEDUCAT, status.bl, APOE4)

# Prepare long table
df.long_censored_funest <- df.long_censored_prc %>%
  select(id, time, event, Years.bl, ADAS13, MMSE, RAVLT.immediate, RAVLT.learning, FAQ) %>%
  rename(obstime = Years.bl) # Use Years.bl instead of age.fup

# Check IDs in long and surv data
all(df.long_censored_funest$id %>% unique() %in% df.surv_preds_funest$id)

df.surv_preds_funest %>% head()
df.long_censored_funest %>% head()
```


## Check NA statistics

```{r}
na_count <- df.long_censored_funest %>%
  group_by(id) %>%
  select_if(function(x) any(is.na(x))) %>%
  summarise_all(funs(sum(is.na(.))))

obs_count <- df.long_censored_funest %>%
  group_by(id) %>%
  select_if(function(x) any(is.na(x))) %>%
  summarise(n())

all(obs_count$id == obs_count$id) # Same id order 

na_count_ratio <- na_count %>% select(-id) / obs_count$`n()`

na_count_ratio %>% summary()

# On average 25% NAs
```


## what is the time to event for survival table?

```{r}
# Test funest on ADNI data

m_funest <- funest_fit(
  df.long_censored_funest %>% filter(id %in% ids), 
  df.surv_preds_funest %>% filter(id %in% ids),
  tv_names = list("ADAS13", "MMSE", "RAVLT.immediate", "RAVLT.learning", "FAQ"),
  fv_names = list("AGE", "PTGENDER", "PTEDUCAT", "status.bl"), 
#  fv_names = list("AGE", "PTGENDER", "PTEDUCAT", "status.bl", "APOE4"), 
  noftree = 100,
  t_star = 3, t_pred = 5)



# t_star: time for the last observed biomarker measurement
# t_pred: time at prediction

predictSurvProb.ranger <- predictor_loader() # must run the following code before calling funest_pred()

res_funest <- funest_pred(
  m_funest,
  df.long_censored_funest %>% filter(id == 30), 
  df.surv_preds_funest %>% filter(id == 30),
  tv_names = list("ADAS13", "MMSE", "RAVLT.immediate", "RAVLT.learning", "FAQ"),
  fv_names = list("AGE", "PTGENDER", "PTEDUCAT", "status.bl"), 
#  fv_names = list("AGE", "PTGENDER", "PTEDUCAT", "status.bl", "APOE4"), 
  t_star = 3, t_pred = 5)
```
## subset example

```{r}
# Prepare surv table
df.surv_preds_funest <- df.surv_preds_prc %>% 
  select(id, time, event, AGE)

# Prepare long table
df.long_censored_funest <- df.long_censored_prc %>%
  select(id, time, event, Years.bl, ADAS13) %>%
  rename(obstime = Years.bl) # Use Years.bl instead of age.fup

# Check IDs in long and surv data
all(df.long_censored_funest$id %>% unique() %in% df.surv_preds_funest$id)

df.surv_preds_funest %>% head()
df.long_censored_funest %>% head()
```

```{r}
df.long_censored_funest %>% select(id) %>% unique() # IDs before na omit

df.long_censored_funest %>% na.omit() %>% select(id) %>% unique() # IDs after na omit

df.long_censored_funest <- df.long_censored_funest %>% na.omit()
```


```{r}
m_funest <- funest_fit(
  df.long_censored_funest, 
  df.surv_preds_funest,
  tv_names = list("ADAS13"),
  fv_names = list("AGE"),
  noftree = 10,
  t_star = 3, t_pred = 5)
```

## after omit NAs

why it works? it does not have to do with NA...

```{r}
# Prepare surv table
df.surv_preds_funest <- df.surv_preds_prc %>% 
  select(id, time, event, AGE, PTGENDER, PTEDUCAT, status.bl, APOE4)

# Prepare long table
df.long_censored_funest <- df.long_censored_prc %>%
  select(id, time, event, Years.bl, ADAS13, MMSE, RAVLT.immediate, RAVLT.learning, FAQ) %>%
  rename(obstime = Years.bl) # Use Years.bl instead of age.fup
```

```{r}
# na.omit step
df.long_censored_funest_clean <- df.long_censored_funest %>% na.omit() # Remove rows with na

df.surv_preds_funest_clean <- df.surv_preds_funest %>% filter(id %in% df.long_censored_funest_clean$id)
```

check removal
```{r}
# IDs before removal
df.long_censored_funest %>% select(id) %>% unique()
# IDs after removal
df.long_censored_funest_clean %>% select(id) %>% unique()
```

```{r}
ids <- df.long_censored_funest_clean %>% rownames() %>% as.integer()
df.long_censored_funest[-ids, ] # Check the rows removed in na.omit
```

```{r}
# Subset id
ids <- sample(df.surv_preds_funest_clean$id, round(nrow(df.surv_preds_funest_clean)*0.5))

```

```{r}
# Test funest on ADNI data

m_funest <- funest_fit(
  df.long_censored_funest_clean %>% filter(id %in% ids), 
  df.surv_preds_funest_clean %>% filter(id %in% ids),
  tv_names = list("ADAS13", "MMSE", "RAVLT.immediate", "RAVLT.learning", "FAQ"),
  fv_names = list("AGE", "PTGENDER", "PTEDUCAT", "status.bl", "APOE4"),
  noftree = 10,
  t_star = 3, t_pred = 5)

# t_star: time for the last observed biomarker measurement
# t_pred: time at prediction
```

```{r}
m_funest
```


# Try to run line by line

```{r}
gen_arg_list = function(n_of_tv, nofp){
  arg_list = list()
  for(i in 1:n_of_tv){
    arg_list[i] = list(list(type = "uFPCA",nbasis = nofp))
  }
  return(arg_list)
}

gen_tv_list = function(n){
  tv_list = list()
  for(i in 1:n){
    tname = paste("Y", as.character(i), sep = '')
    tv_list[[tname]] = list()
  }
  return(tv_list)
}
```


```{r}
long_train <- df.long_censored_funest
surv_train <- df.surv_preds_funest
tv_names <- list("ADAS13", "MMSE", "RAVLT.immediate", "RAVLT.learning", "FAQ")
fv_names <- list("AGE", "PTGENDER", "PTEDUCAT", "status.bl", "APOE4")
t_star <- 3
t_pred <- 5

noftree = 10

nofcov = 2
split_rule = "maxstat"
nofp = 3
  
  
# find number of unique individuals in training sample and test sample
max_time = max(surv_train$time)
if(t_star >= t_pred){
  stop("t_star must be smaller than t_pred!")
}
if(t_pred > max_time){
  stop("t_pred must be smaller than maximum observation time in the dataset!")
}


train_patID = surv_train$id # get subject ids and number of subjects
train_npat = length(train_patID) # get subject ids and number of subjects

# Format long data 
n_of_tv = length(tv_names) # count long variables
train_tv_list = gen_tv_list(n_of_tv) # initiate a list for each long variable, contain # of subjects lists with sublists corresponding to each long variable
train_time_list = list() # a list of list of obs time for each subject, list length = # of subjects

for(i in 1:train_npat){
  # For each patient
  tid = train_patID[i] # select subject i
  tdat = long_train[long_train$id == tid,] # subset by filter subject i
  train_time_list = c(train_time_list, list(tdat$obstime)) # obs time for subject i
  temp_tv = tdat[, unlist(tv_names)] # subset long variable columns
  
  for(j in 1:n_of_tv){
    # For each long variable
    ttv = as.vector(temp_tv[j])[,1] # convert each long variable in vector
    train_tv_list[[j]] = c(train_tv_list[[j]], list(ttv)) # join list
  }
}
```

```{r}
train_tfobj = gen_tv_list(n_of_tv)
# problematic lines
for(k in 1:n_of_tv){
  # For each long variable
  train_tfobj[[k]] = funData::as.funData(funData::irregFunData(
    argvals = train_time_list, 
    X = train_tv_list[[k]]))
}


```

```{r}
# detail look
# example
# when k = 1, meaning first long variable ADAS13
# for second subject

#train_tv_list[[1]][[2]]
#train_time_list[[2]]

funData::as.funData( # coerces an object of class `irregFunData` to a `funData` object with missing values, which is defined on the union of all observation points
  funData::irregFunData( # represents functional data that is sampled irregularly on one-dimensional domains. The two slots represent the observation points (x) and the observed function values (y)
    argvals = train_time_list, 
    X = train_tv_list[[1]])
)
```



```{r}
# check irregFunData

# error when k = 1
test <- funData::irregFunData(
    argvals = train_time_list, # A list of numerics, corresponding to the observation points for each realization X_i
    X = train_tv_list[[1]]) # A list of numerics, corresponding to the observed functions X_i

summary(test)

```


```{r}

# Testing irregfundata
# NOT RUN {
# Construct an irregular functional data object
i1 <- funData::irregFunData(argvals = list(1:5, 2:4), X = list(2:6, 3:5))
# Display in the console
i1
# Summarize
summary(i1)

# A more realistic object
argvals <- seq(0,2*pi, 0.01)
ind <- replicate(11, sort(sample(1:length(argvals), sample(5:10,1)))) # sample observation points
argvalsIrreg <- lapply(ind, function(i){argvals[i]})
i2 <- funData::irregFunData(argvals = argvalsIrreg, X = mapply(function(x, a){a * sin(x)},
             x = argvalsIrreg, a = seq(0.75, 1.25, by = 0.05)))
# Display/summary gives basic information
i2
summary(i2)
# Use the plot function to get an impression of the data
plot(i2) 
# }
```


```{r}
train_mfobj = funData::multiFunData(train_tfobj)

arg_list = gen_arg_list(n_of_tv, nofp)

train_mfpca = MFPCA::MFPCA(train_mfobj, M = nofp,
                    uniExpansions = arg_list)

train_scores = train_mfpca$scores
train_funs = train_mfpca$vectors

train_covs = cbind(train_scores, surv_train[,unlist(fv_names)])
d_delta = ncol(train_covs)

score_names = c()
for(q in 1:(d_delta)){
  tname = paste("score", as.character(q), sep = "")
  score_names = c(score_names, tname)
}
colnames(train_covs) = score_names

train_data.sub = cbind(surv_train, train_covs)

# specify model formula
fmla = stats::as.formula(paste("Surv(time,event) ~ ",
                        paste(score_names, collapse= "+")))

# Outputs

# Random forest model
rg = ranger::ranger(
  fmla, 
  data = train_data.sub, 
  num.trees = noftree,
  mtry = nofcov, 
  splitrule = split_rule, ...)

# Model inputs
misc = list(
  long_train = long_train,
  surv_train = surv_train,
  fmla = fmla,
  score_names = score_names,
  nofp = nofp,
  train_data.sub = train_data.sub
)
```

```{r}
  return(list(misc = misc,
              rg = rg
              ))
}
```


